fix: missing null check in braze populateCustomAttributesWithOperation
Found logs for this error:
Failure occurred during custom attributes operations
TypeError: Cannot read properties of null (reading 'update')